
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TravelPlan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TravelPlan
 * 
 */
export type TravelPlanModel = runtime.Types.Result.DefaultSelection<Prisma.$TravelPlanPayload>

export type AggregateTravelPlan = {
  _count: TravelPlanCountAggregateOutputType | null
  _min: TravelPlanMinAggregateOutputType | null
  _max: TravelPlanMaxAggregateOutputType | null
}

export type TravelPlanMinAggregateOutputType = {
  id: string | null
  title: string | null
  destination: string | null
  startDate: Date | null
  endDate: Date | null
  budgetRange: string | null
  travelType: $Enums.TravelType | null
  description: string | null
  visibility: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  authorId: string | null
}

export type TravelPlanMaxAggregateOutputType = {
  id: string | null
  title: string | null
  destination: string | null
  startDate: Date | null
  endDate: Date | null
  budgetRange: string | null
  travelType: $Enums.TravelType | null
  description: string | null
  visibility: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  authorId: string | null
}

export type TravelPlanCountAggregateOutputType = {
  id: number
  title: number
  destination: number
  startDate: number
  endDate: number
  budgetRange: number
  travelType: number
  description: number
  visibility: number
  images: number
  createdAt: number
  updatedAt: number
  authorId: number
  _all: number
}


export type TravelPlanMinAggregateInputType = {
  id?: true
  title?: true
  destination?: true
  startDate?: true
  endDate?: true
  budgetRange?: true
  travelType?: true
  description?: true
  visibility?: true
  createdAt?: true
  updatedAt?: true
  authorId?: true
}

export type TravelPlanMaxAggregateInputType = {
  id?: true
  title?: true
  destination?: true
  startDate?: true
  endDate?: true
  budgetRange?: true
  travelType?: true
  description?: true
  visibility?: true
  createdAt?: true
  updatedAt?: true
  authorId?: true
}

export type TravelPlanCountAggregateInputType = {
  id?: true
  title?: true
  destination?: true
  startDate?: true
  endDate?: true
  budgetRange?: true
  travelType?: true
  description?: true
  visibility?: true
  images?: true
  createdAt?: true
  updatedAt?: true
  authorId?: true
  _all?: true
}

export type TravelPlanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TravelPlan to aggregate.
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TravelPlans to fetch.
   */
  orderBy?: Prisma.TravelPlanOrderByWithRelationInput | Prisma.TravelPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TravelPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TravelPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TravelPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TravelPlans
  **/
  _count?: true | TravelPlanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TravelPlanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TravelPlanMaxAggregateInputType
}

export type GetTravelPlanAggregateType<T extends TravelPlanAggregateArgs> = {
      [P in keyof T & keyof AggregateTravelPlan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTravelPlan[P]>
    : Prisma.GetScalarType<T[P], AggregateTravelPlan[P]>
}




export type TravelPlanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TravelPlanWhereInput
  orderBy?: Prisma.TravelPlanOrderByWithAggregationInput | Prisma.TravelPlanOrderByWithAggregationInput[]
  by: Prisma.TravelPlanScalarFieldEnum[] | Prisma.TravelPlanScalarFieldEnum
  having?: Prisma.TravelPlanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TravelPlanCountAggregateInputType | true
  _min?: TravelPlanMinAggregateInputType
  _max?: TravelPlanMaxAggregateInputType
}

export type TravelPlanGroupByOutputType = {
  id: string
  title: string
  destination: string
  startDate: Date
  endDate: Date
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility: boolean
  images: string[]
  createdAt: Date
  updatedAt: Date
  authorId: string
  _count: TravelPlanCountAggregateOutputType | null
  _min: TravelPlanMinAggregateOutputType | null
  _max: TravelPlanMaxAggregateOutputType | null
}

type GetTravelPlanGroupByPayload<T extends TravelPlanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TravelPlanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TravelPlanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TravelPlanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TravelPlanGroupByOutputType[P]>
      }
    >
  >



export type TravelPlanWhereInput = {
  AND?: Prisma.TravelPlanWhereInput | Prisma.TravelPlanWhereInput[]
  OR?: Prisma.TravelPlanWhereInput[]
  NOT?: Prisma.TravelPlanWhereInput | Prisma.TravelPlanWhereInput[]
  id?: Prisma.StringFilter<"TravelPlan"> | string
  title?: Prisma.StringFilter<"TravelPlan"> | string
  destination?: Prisma.StringFilter<"TravelPlan"> | string
  startDate?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  endDate?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  budgetRange?: Prisma.StringFilter<"TravelPlan"> | string
  travelType?: Prisma.EnumTravelTypeFilter<"TravelPlan"> | $Enums.TravelType
  description?: Prisma.StringFilter<"TravelPlan"> | string
  visibility?: Prisma.BoolFilter<"TravelPlan"> | boolean
  images?: Prisma.StringNullableListFilter<"TravelPlan">
  createdAt?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  authorId?: Prisma.StringFilter<"TravelPlan"> | string
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  requests?: Prisma.RequestListRelationFilter
}

export type TravelPlanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  budgetRange?: Prisma.SortOrder
  travelType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  images?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  author?: Prisma.UserOrderByWithRelationInput
  requests?: Prisma.RequestOrderByRelationAggregateInput
}

export type TravelPlanWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TravelPlanWhereInput | Prisma.TravelPlanWhereInput[]
  OR?: Prisma.TravelPlanWhereInput[]
  NOT?: Prisma.TravelPlanWhereInput | Prisma.TravelPlanWhereInput[]
  title?: Prisma.StringFilter<"TravelPlan"> | string
  destination?: Prisma.StringFilter<"TravelPlan"> | string
  startDate?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  endDate?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  budgetRange?: Prisma.StringFilter<"TravelPlan"> | string
  travelType?: Prisma.EnumTravelTypeFilter<"TravelPlan"> | $Enums.TravelType
  description?: Prisma.StringFilter<"TravelPlan"> | string
  visibility?: Prisma.BoolFilter<"TravelPlan"> | boolean
  images?: Prisma.StringNullableListFilter<"TravelPlan">
  createdAt?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  authorId?: Prisma.StringFilter<"TravelPlan"> | string
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  requests?: Prisma.RequestListRelationFilter
}, "id">

export type TravelPlanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  budgetRange?: Prisma.SortOrder
  travelType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  images?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  _count?: Prisma.TravelPlanCountOrderByAggregateInput
  _max?: Prisma.TravelPlanMaxOrderByAggregateInput
  _min?: Prisma.TravelPlanMinOrderByAggregateInput
}

export type TravelPlanScalarWhereWithAggregatesInput = {
  AND?: Prisma.TravelPlanScalarWhereWithAggregatesInput | Prisma.TravelPlanScalarWhereWithAggregatesInput[]
  OR?: Prisma.TravelPlanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TravelPlanScalarWhereWithAggregatesInput | Prisma.TravelPlanScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TravelPlan"> | string
  title?: Prisma.StringWithAggregatesFilter<"TravelPlan"> | string
  destination?: Prisma.StringWithAggregatesFilter<"TravelPlan"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"TravelPlan"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"TravelPlan"> | Date | string
  budgetRange?: Prisma.StringWithAggregatesFilter<"TravelPlan"> | string
  travelType?: Prisma.EnumTravelTypeWithAggregatesFilter<"TravelPlan"> | $Enums.TravelType
  description?: Prisma.StringWithAggregatesFilter<"TravelPlan"> | string
  visibility?: Prisma.BoolWithAggregatesFilter<"TravelPlan"> | boolean
  images?: Prisma.StringNullableListFilter<"TravelPlan">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TravelPlan"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TravelPlan"> | Date | string
  authorId?: Prisma.StringWithAggregatesFilter<"TravelPlan"> | string
}

export type TravelPlanCreateInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  author: Prisma.UserCreateNestedOneWithoutTravelPlansInput
  requests?: Prisma.RequestCreateNestedManyWithoutTravelPlanInput
}

export type TravelPlanUncheckedCreateInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  authorId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutTravelPlanInput
}

export type TravelPlanUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneRequiredWithoutTravelPlansNestedInput
  requests?: Prisma.RequestUpdateManyWithoutTravelPlanNestedInput
}

export type TravelPlanUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutTravelPlanNestedInput
}

export type TravelPlanCreateManyInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  authorId: string
}

export type TravelPlanUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TravelPlanUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TravelPlanScalarRelationFilter = {
  is?: Prisma.TravelPlanWhereInput
  isNot?: Prisma.TravelPlanWhereInput
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type TravelPlanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  budgetRange?: Prisma.SortOrder
  travelType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  images?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
}

export type TravelPlanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  budgetRange?: Prisma.SortOrder
  travelType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
}

export type TravelPlanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  budgetRange?: Prisma.SortOrder
  travelType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
}

export type TravelPlanListRelationFilter = {
  every?: Prisma.TravelPlanWhereInput
  some?: Prisma.TravelPlanWhereInput
  none?: Prisma.TravelPlanWhereInput
}

export type TravelPlanOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TravelPlanCreateNestedOneWithoutRequestsInput = {
  create?: Prisma.XOR<Prisma.TravelPlanCreateWithoutRequestsInput, Prisma.TravelPlanUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.TravelPlanCreateOrConnectWithoutRequestsInput
  connect?: Prisma.TravelPlanWhereUniqueInput
}

export type TravelPlanUpdateOneRequiredWithoutRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.TravelPlanCreateWithoutRequestsInput, Prisma.TravelPlanUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.TravelPlanCreateOrConnectWithoutRequestsInput
  upsert?: Prisma.TravelPlanUpsertWithoutRequestsInput
  connect?: Prisma.TravelPlanWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TravelPlanUpdateToOneWithWhereWithoutRequestsInput, Prisma.TravelPlanUpdateWithoutRequestsInput>, Prisma.TravelPlanUncheckedUpdateWithoutRequestsInput>
}

export type TravelPlanCreateimagesInput = {
  set: string[]
}

export type EnumTravelTypeFieldUpdateOperationsInput = {
  set?: $Enums.TravelType
}

export type TravelPlanUpdateimagesInput = {
  set?: string[]
  push?: string | string[]
}

export type TravelPlanCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TravelPlanCreateWithoutAuthorInput, Prisma.TravelPlanUncheckedCreateWithoutAuthorInput> | Prisma.TravelPlanCreateWithoutAuthorInput[] | Prisma.TravelPlanUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TravelPlanCreateOrConnectWithoutAuthorInput | Prisma.TravelPlanCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TravelPlanCreateManyAuthorInputEnvelope
  connect?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
}

export type TravelPlanUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TravelPlanCreateWithoutAuthorInput, Prisma.TravelPlanUncheckedCreateWithoutAuthorInput> | Prisma.TravelPlanCreateWithoutAuthorInput[] | Prisma.TravelPlanUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TravelPlanCreateOrConnectWithoutAuthorInput | Prisma.TravelPlanCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TravelPlanCreateManyAuthorInputEnvelope
  connect?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
}

export type TravelPlanUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TravelPlanCreateWithoutAuthorInput, Prisma.TravelPlanUncheckedCreateWithoutAuthorInput> | Prisma.TravelPlanCreateWithoutAuthorInput[] | Prisma.TravelPlanUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TravelPlanCreateOrConnectWithoutAuthorInput | Prisma.TravelPlanCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TravelPlanUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TravelPlanUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TravelPlanCreateManyAuthorInputEnvelope
  set?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  disconnect?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  delete?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  connect?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  update?: Prisma.TravelPlanUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TravelPlanUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TravelPlanUpdateManyWithWhereWithoutAuthorInput | Prisma.TravelPlanUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TravelPlanScalarWhereInput | Prisma.TravelPlanScalarWhereInput[]
}

export type TravelPlanUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TravelPlanCreateWithoutAuthorInput, Prisma.TravelPlanUncheckedCreateWithoutAuthorInput> | Prisma.TravelPlanCreateWithoutAuthorInput[] | Prisma.TravelPlanUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TravelPlanCreateOrConnectWithoutAuthorInput | Prisma.TravelPlanCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TravelPlanUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TravelPlanUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TravelPlanCreateManyAuthorInputEnvelope
  set?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  disconnect?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  delete?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  connect?: Prisma.TravelPlanWhereUniqueInput | Prisma.TravelPlanWhereUniqueInput[]
  update?: Prisma.TravelPlanUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TravelPlanUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TravelPlanUpdateManyWithWhereWithoutAuthorInput | Prisma.TravelPlanUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TravelPlanScalarWhereInput | Prisma.TravelPlanScalarWhereInput[]
}

export type TravelPlanCreateWithoutRequestsInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  author: Prisma.UserCreateNestedOneWithoutTravelPlansInput
}

export type TravelPlanUncheckedCreateWithoutRequestsInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  authorId: string
}

export type TravelPlanCreateOrConnectWithoutRequestsInput = {
  where: Prisma.TravelPlanWhereUniqueInput
  create: Prisma.XOR<Prisma.TravelPlanCreateWithoutRequestsInput, Prisma.TravelPlanUncheckedCreateWithoutRequestsInput>
}

export type TravelPlanUpsertWithoutRequestsInput = {
  update: Prisma.XOR<Prisma.TravelPlanUpdateWithoutRequestsInput, Prisma.TravelPlanUncheckedUpdateWithoutRequestsInput>
  create: Prisma.XOR<Prisma.TravelPlanCreateWithoutRequestsInput, Prisma.TravelPlanUncheckedCreateWithoutRequestsInput>
  where?: Prisma.TravelPlanWhereInput
}

export type TravelPlanUpdateToOneWithWhereWithoutRequestsInput = {
  where?: Prisma.TravelPlanWhereInput
  data: Prisma.XOR<Prisma.TravelPlanUpdateWithoutRequestsInput, Prisma.TravelPlanUncheckedUpdateWithoutRequestsInput>
}

export type TravelPlanUpdateWithoutRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneRequiredWithoutTravelPlansNestedInput
}

export type TravelPlanUncheckedUpdateWithoutRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TravelPlanCreateWithoutAuthorInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  requests?: Prisma.RequestCreateNestedManyWithoutTravelPlanInput
}

export type TravelPlanUncheckedCreateWithoutAuthorInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutTravelPlanInput
}

export type TravelPlanCreateOrConnectWithoutAuthorInput = {
  where: Prisma.TravelPlanWhereUniqueInput
  create: Prisma.XOR<Prisma.TravelPlanCreateWithoutAuthorInput, Prisma.TravelPlanUncheckedCreateWithoutAuthorInput>
}

export type TravelPlanCreateManyAuthorInputEnvelope = {
  data: Prisma.TravelPlanCreateManyAuthorInput | Prisma.TravelPlanCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type TravelPlanUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TravelPlanWhereUniqueInput
  update: Prisma.XOR<Prisma.TravelPlanUpdateWithoutAuthorInput, Prisma.TravelPlanUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.TravelPlanCreateWithoutAuthorInput, Prisma.TravelPlanUncheckedCreateWithoutAuthorInput>
}

export type TravelPlanUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TravelPlanWhereUniqueInput
  data: Prisma.XOR<Prisma.TravelPlanUpdateWithoutAuthorInput, Prisma.TravelPlanUncheckedUpdateWithoutAuthorInput>
}

export type TravelPlanUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.TravelPlanScalarWhereInput
  data: Prisma.XOR<Prisma.TravelPlanUpdateManyMutationInput, Prisma.TravelPlanUncheckedUpdateManyWithoutAuthorInput>
}

export type TravelPlanScalarWhereInput = {
  AND?: Prisma.TravelPlanScalarWhereInput | Prisma.TravelPlanScalarWhereInput[]
  OR?: Prisma.TravelPlanScalarWhereInput[]
  NOT?: Prisma.TravelPlanScalarWhereInput | Prisma.TravelPlanScalarWhereInput[]
  id?: Prisma.StringFilter<"TravelPlan"> | string
  title?: Prisma.StringFilter<"TravelPlan"> | string
  destination?: Prisma.StringFilter<"TravelPlan"> | string
  startDate?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  endDate?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  budgetRange?: Prisma.StringFilter<"TravelPlan"> | string
  travelType?: Prisma.EnumTravelTypeFilter<"TravelPlan"> | $Enums.TravelType
  description?: Prisma.StringFilter<"TravelPlan"> | string
  visibility?: Prisma.BoolFilter<"TravelPlan"> | boolean
  images?: Prisma.StringNullableListFilter<"TravelPlan">
  createdAt?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TravelPlan"> | Date | string
  authorId?: Prisma.StringFilter<"TravelPlan"> | string
}

export type TravelPlanCreateManyAuthorInput = {
  id?: string
  title: string
  destination: string
  startDate: Date | string
  endDate: Date | string
  budgetRange: string
  travelType: $Enums.TravelType
  description: string
  visibility?: boolean
  images?: Prisma.TravelPlanCreateimagesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TravelPlanUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  requests?: Prisma.RequestUpdateManyWithoutTravelPlanNestedInput
}

export type TravelPlanUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutTravelPlanNestedInput
}

export type TravelPlanUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgetRange?: Prisma.StringFieldUpdateOperationsInput | string
  travelType?: Prisma.EnumTravelTypeFieldUpdateOperationsInput | $Enums.TravelType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.BoolFieldUpdateOperationsInput | boolean
  images?: Prisma.TravelPlanUpdateimagesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TravelPlanCountOutputType
 */

export type TravelPlanCountOutputType = {
  requests: number
}

export type TravelPlanCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requests?: boolean | TravelPlanCountOutputTypeCountRequestsArgs
}

/**
 * TravelPlanCountOutputType without action
 */
export type TravelPlanCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlanCountOutputType
   */
  select?: Prisma.TravelPlanCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TravelPlanCountOutputType without action
 */
export type TravelPlanCountOutputTypeCountRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestWhereInput
}


export type TravelPlanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  destination?: boolean
  startDate?: boolean
  endDate?: boolean
  budgetRange?: boolean
  travelType?: boolean
  description?: boolean
  visibility?: boolean
  images?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  authorId?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  requests?: boolean | Prisma.TravelPlan$requestsArgs<ExtArgs>
  _count?: boolean | Prisma.TravelPlanCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["travelPlan"]>

export type TravelPlanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  destination?: boolean
  startDate?: boolean
  endDate?: boolean
  budgetRange?: boolean
  travelType?: boolean
  description?: boolean
  visibility?: boolean
  images?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  authorId?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["travelPlan"]>

export type TravelPlanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  destination?: boolean
  startDate?: boolean
  endDate?: boolean
  budgetRange?: boolean
  travelType?: boolean
  description?: boolean
  visibility?: boolean
  images?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  authorId?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["travelPlan"]>

export type TravelPlanSelectScalar = {
  id?: boolean
  title?: boolean
  destination?: boolean
  startDate?: boolean
  endDate?: boolean
  budgetRange?: boolean
  travelType?: boolean
  description?: boolean
  visibility?: boolean
  images?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  authorId?: boolean
}

export type TravelPlanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "destination" | "startDate" | "endDate" | "budgetRange" | "travelType" | "description" | "visibility" | "images" | "createdAt" | "updatedAt" | "authorId", ExtArgs["result"]["travelPlan"]>
export type TravelPlanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  requests?: boolean | Prisma.TravelPlan$requestsArgs<ExtArgs>
  _count?: boolean | Prisma.TravelPlanCountOutputTypeDefaultArgs<ExtArgs>
}
export type TravelPlanIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TravelPlanIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TravelPlanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TravelPlan"
  objects: {
    author: Prisma.$UserPayload<ExtArgs>
    requests: Prisma.$RequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    destination: string
    startDate: Date
    endDate: Date
    budgetRange: string
    travelType: $Enums.TravelType
    description: string
    visibility: boolean
    images: string[]
    createdAt: Date
    updatedAt: Date
    authorId: string
  }, ExtArgs["result"]["travelPlan"]>
  composites: {}
}

export type TravelPlanGetPayload<S extends boolean | null | undefined | TravelPlanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload, S>

export type TravelPlanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TravelPlanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TravelPlanCountAggregateInputType | true
  }

export interface TravelPlanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TravelPlan'], meta: { name: 'TravelPlan' } }
  /**
   * Find zero or one TravelPlan that matches the filter.
   * @param {TravelPlanFindUniqueArgs} args - Arguments to find a TravelPlan
   * @example
   * // Get one TravelPlan
   * const travelPlan = await prisma.travelPlan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TravelPlanFindUniqueArgs>(args: Prisma.SelectSubset<T, TravelPlanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TravelPlan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TravelPlanFindUniqueOrThrowArgs} args - Arguments to find a TravelPlan
   * @example
   * // Get one TravelPlan
   * const travelPlan = await prisma.travelPlan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TravelPlanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TravelPlanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TravelPlan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanFindFirstArgs} args - Arguments to find a TravelPlan
   * @example
   * // Get one TravelPlan
   * const travelPlan = await prisma.travelPlan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TravelPlanFindFirstArgs>(args?: Prisma.SelectSubset<T, TravelPlanFindFirstArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TravelPlan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanFindFirstOrThrowArgs} args - Arguments to find a TravelPlan
   * @example
   * // Get one TravelPlan
   * const travelPlan = await prisma.travelPlan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TravelPlanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TravelPlanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TravelPlans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TravelPlans
   * const travelPlans = await prisma.travelPlan.findMany()
   * 
   * // Get first 10 TravelPlans
   * const travelPlans = await prisma.travelPlan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const travelPlanWithIdOnly = await prisma.travelPlan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TravelPlanFindManyArgs>(args?: Prisma.SelectSubset<T, TravelPlanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TravelPlan.
   * @param {TravelPlanCreateArgs} args - Arguments to create a TravelPlan.
   * @example
   * // Create one TravelPlan
   * const TravelPlan = await prisma.travelPlan.create({
   *   data: {
   *     // ... data to create a TravelPlan
   *   }
   * })
   * 
   */
  create<T extends TravelPlanCreateArgs>(args: Prisma.SelectSubset<T, TravelPlanCreateArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TravelPlans.
   * @param {TravelPlanCreateManyArgs} args - Arguments to create many TravelPlans.
   * @example
   * // Create many TravelPlans
   * const travelPlan = await prisma.travelPlan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TravelPlanCreateManyArgs>(args?: Prisma.SelectSubset<T, TravelPlanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TravelPlans and returns the data saved in the database.
   * @param {TravelPlanCreateManyAndReturnArgs} args - Arguments to create many TravelPlans.
   * @example
   * // Create many TravelPlans
   * const travelPlan = await prisma.travelPlan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TravelPlans and only return the `id`
   * const travelPlanWithIdOnly = await prisma.travelPlan.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TravelPlanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TravelPlanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TravelPlan.
   * @param {TravelPlanDeleteArgs} args - Arguments to delete one TravelPlan.
   * @example
   * // Delete one TravelPlan
   * const TravelPlan = await prisma.travelPlan.delete({
   *   where: {
   *     // ... filter to delete one TravelPlan
   *   }
   * })
   * 
   */
  delete<T extends TravelPlanDeleteArgs>(args: Prisma.SelectSubset<T, TravelPlanDeleteArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TravelPlan.
   * @param {TravelPlanUpdateArgs} args - Arguments to update one TravelPlan.
   * @example
   * // Update one TravelPlan
   * const travelPlan = await prisma.travelPlan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TravelPlanUpdateArgs>(args: Prisma.SelectSubset<T, TravelPlanUpdateArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TravelPlans.
   * @param {TravelPlanDeleteManyArgs} args - Arguments to filter TravelPlans to delete.
   * @example
   * // Delete a few TravelPlans
   * const { count } = await prisma.travelPlan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TravelPlanDeleteManyArgs>(args?: Prisma.SelectSubset<T, TravelPlanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TravelPlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TravelPlans
   * const travelPlan = await prisma.travelPlan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TravelPlanUpdateManyArgs>(args: Prisma.SelectSubset<T, TravelPlanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TravelPlans and returns the data updated in the database.
   * @param {TravelPlanUpdateManyAndReturnArgs} args - Arguments to update many TravelPlans.
   * @example
   * // Update many TravelPlans
   * const travelPlan = await prisma.travelPlan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TravelPlans and only return the `id`
   * const travelPlanWithIdOnly = await prisma.travelPlan.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TravelPlanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TravelPlanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TravelPlan.
   * @param {TravelPlanUpsertArgs} args - Arguments to update or create a TravelPlan.
   * @example
   * // Update or create a TravelPlan
   * const travelPlan = await prisma.travelPlan.upsert({
   *   create: {
   *     // ... data to create a TravelPlan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TravelPlan we want to update
   *   }
   * })
   */
  upsert<T extends TravelPlanUpsertArgs>(args: Prisma.SelectSubset<T, TravelPlanUpsertArgs<ExtArgs>>): Prisma.Prisma__TravelPlanClient<runtime.Types.Result.GetResult<Prisma.$TravelPlanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TravelPlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanCountArgs} args - Arguments to filter TravelPlans to count.
   * @example
   * // Count the number of TravelPlans
   * const count = await prisma.travelPlan.count({
   *   where: {
   *     // ... the filter for the TravelPlans we want to count
   *   }
   * })
  **/
  count<T extends TravelPlanCountArgs>(
    args?: Prisma.Subset<T, TravelPlanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TravelPlanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TravelPlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TravelPlanAggregateArgs>(args: Prisma.Subset<T, TravelPlanAggregateArgs>): Prisma.PrismaPromise<GetTravelPlanAggregateType<T>>

  /**
   * Group by TravelPlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TravelPlanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TravelPlanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TravelPlanGroupByArgs['orderBy'] }
      : { orderBy?: TravelPlanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TravelPlanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTravelPlanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TravelPlan model
 */
readonly fields: TravelPlanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TravelPlan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TravelPlanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  requests<T extends Prisma.TravelPlan$requestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TravelPlan$requestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TravelPlan model
 */
export interface TravelPlanFieldRefs {
  readonly id: Prisma.FieldRef<"TravelPlan", 'String'>
  readonly title: Prisma.FieldRef<"TravelPlan", 'String'>
  readonly destination: Prisma.FieldRef<"TravelPlan", 'String'>
  readonly startDate: Prisma.FieldRef<"TravelPlan", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"TravelPlan", 'DateTime'>
  readonly budgetRange: Prisma.FieldRef<"TravelPlan", 'String'>
  readonly travelType: Prisma.FieldRef<"TravelPlan", 'TravelType'>
  readonly description: Prisma.FieldRef<"TravelPlan", 'String'>
  readonly visibility: Prisma.FieldRef<"TravelPlan", 'Boolean'>
  readonly images: Prisma.FieldRef<"TravelPlan", 'String[]'>
  readonly createdAt: Prisma.FieldRef<"TravelPlan", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TravelPlan", 'DateTime'>
  readonly authorId: Prisma.FieldRef<"TravelPlan", 'String'>
}
    

// Custom InputTypes
/**
 * TravelPlan findUnique
 */
export type TravelPlanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * Filter, which TravelPlan to fetch.
   */
  where: Prisma.TravelPlanWhereUniqueInput
}

/**
 * TravelPlan findUniqueOrThrow
 */
export type TravelPlanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * Filter, which TravelPlan to fetch.
   */
  where: Prisma.TravelPlanWhereUniqueInput
}

/**
 * TravelPlan findFirst
 */
export type TravelPlanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * Filter, which TravelPlan to fetch.
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TravelPlans to fetch.
   */
  orderBy?: Prisma.TravelPlanOrderByWithRelationInput | Prisma.TravelPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TravelPlans.
   */
  cursor?: Prisma.TravelPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TravelPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TravelPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TravelPlans.
   */
  distinct?: Prisma.TravelPlanScalarFieldEnum | Prisma.TravelPlanScalarFieldEnum[]
}

/**
 * TravelPlan findFirstOrThrow
 */
export type TravelPlanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * Filter, which TravelPlan to fetch.
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TravelPlans to fetch.
   */
  orderBy?: Prisma.TravelPlanOrderByWithRelationInput | Prisma.TravelPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TravelPlans.
   */
  cursor?: Prisma.TravelPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TravelPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TravelPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TravelPlans.
   */
  distinct?: Prisma.TravelPlanScalarFieldEnum | Prisma.TravelPlanScalarFieldEnum[]
}

/**
 * TravelPlan findMany
 */
export type TravelPlanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * Filter, which TravelPlans to fetch.
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TravelPlans to fetch.
   */
  orderBy?: Prisma.TravelPlanOrderByWithRelationInput | Prisma.TravelPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TravelPlans.
   */
  cursor?: Prisma.TravelPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TravelPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TravelPlans.
   */
  skip?: number
  distinct?: Prisma.TravelPlanScalarFieldEnum | Prisma.TravelPlanScalarFieldEnum[]
}

/**
 * TravelPlan create
 */
export type TravelPlanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * The data needed to create a TravelPlan.
   */
  data: Prisma.XOR<Prisma.TravelPlanCreateInput, Prisma.TravelPlanUncheckedCreateInput>
}

/**
 * TravelPlan createMany
 */
export type TravelPlanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TravelPlans.
   */
  data: Prisma.TravelPlanCreateManyInput | Prisma.TravelPlanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TravelPlan createManyAndReturn
 */
export type TravelPlanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * The data used to create many TravelPlans.
   */
  data: Prisma.TravelPlanCreateManyInput | Prisma.TravelPlanCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TravelPlan update
 */
export type TravelPlanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * The data needed to update a TravelPlan.
   */
  data: Prisma.XOR<Prisma.TravelPlanUpdateInput, Prisma.TravelPlanUncheckedUpdateInput>
  /**
   * Choose, which TravelPlan to update.
   */
  where: Prisma.TravelPlanWhereUniqueInput
}

/**
 * TravelPlan updateMany
 */
export type TravelPlanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TravelPlans.
   */
  data: Prisma.XOR<Prisma.TravelPlanUpdateManyMutationInput, Prisma.TravelPlanUncheckedUpdateManyInput>
  /**
   * Filter which TravelPlans to update
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * Limit how many TravelPlans to update.
   */
  limit?: number
}

/**
 * TravelPlan updateManyAndReturn
 */
export type TravelPlanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * The data used to update TravelPlans.
   */
  data: Prisma.XOR<Prisma.TravelPlanUpdateManyMutationInput, Prisma.TravelPlanUncheckedUpdateManyInput>
  /**
   * Filter which TravelPlans to update
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * Limit how many TravelPlans to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TravelPlan upsert
 */
export type TravelPlanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * The filter to search for the TravelPlan to update in case it exists.
   */
  where: Prisma.TravelPlanWhereUniqueInput
  /**
   * In case the TravelPlan found by the `where` argument doesn't exist, create a new TravelPlan with this data.
   */
  create: Prisma.XOR<Prisma.TravelPlanCreateInput, Prisma.TravelPlanUncheckedCreateInput>
  /**
   * In case the TravelPlan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TravelPlanUpdateInput, Prisma.TravelPlanUncheckedUpdateInput>
}

/**
 * TravelPlan delete
 */
export type TravelPlanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
  /**
   * Filter which TravelPlan to delete.
   */
  where: Prisma.TravelPlanWhereUniqueInput
}

/**
 * TravelPlan deleteMany
 */
export type TravelPlanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TravelPlans to delete
   */
  where?: Prisma.TravelPlanWhereInput
  /**
   * Limit how many TravelPlans to delete.
   */
  limit?: number
}

/**
 * TravelPlan.requests
 */
export type TravelPlan$requestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Request
   */
  select?: Prisma.RequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Request
   */
  omit?: Prisma.RequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestInclude<ExtArgs> | null
  where?: Prisma.RequestWhereInput
  orderBy?: Prisma.RequestOrderByWithRelationInput | Prisma.RequestOrderByWithRelationInput[]
  cursor?: Prisma.RequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestScalarFieldEnum | Prisma.RequestScalarFieldEnum[]
}

/**
 * TravelPlan without action
 */
export type TravelPlanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TravelPlan
   */
  select?: Prisma.TravelPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TravelPlan
   */
  omit?: Prisma.TravelPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TravelPlanInclude<ExtArgs> | null
}
