
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const TravelType = {
  SOLO: 'SOLO',
  FAMILY: 'FAMILY',
  FRIENDS: 'FRIENDS'
} as const

export type TravelType = (typeof TravelType)[keyof typeof TravelType]


export const PlanType = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
} as const

export type PlanType = (typeof PlanType)[keyof typeof PlanType]


export const PaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const RequestStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
} as const

export type RequestStatus = (typeof RequestStatus)[keyof typeof RequestStatus]
